[tool.poetry]
name = "qumat"
version = "0.0.1"
description = "A library for composing quantum machine learning."
authors = ["rawkintrevo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
qiskit = "^0.45.1"
qiskit-aer = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
